language: java
jdk:
    - oraclejdk8
sudo: false
env:
    - EXTRA_JAVA_HOMES=/usr/lib/jvm/java-8-oracle
script:
    - ./mx.sh --vm server build
    - ./mx.sh --vm server unittest
    - ./mx.sh --vm server checkheaders
    - ./mx.sh --vm server checkcopyright
    - ./mx.sh --vm server checkstyle
    - ./mx.sh --vm server findbugs
